In [2]:
import numpy as np

a=[i for i in range(1,100)]
b=np.arange(100)

print(a)
print(b)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [9]:
import sys

print(b.itemsize)
print(sys.getsizeof(3))

8
28


In [25]:
b=np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [28]:
import numpy as np
ary = np.array([1,2,3,5,8])
ary = ary + 6.3
print (ary[1])

8.3


In [29]:
a = np.empty(4, dtype = int)
print(a)

[            0 1422582354256 1422582357616 1422582354896]


In [34]:
a=a+[1,2,3,4]
a=a+16
a

array([           44, 1422582354301, 1422582357662, 1422582354943])

In [44]:
ary=np.arange(2,10,2)
ary

array([2, 4, 6, 8])

In [82]:
import pylab as p

aray=np.linspace(20,2,10,endpoint=True,retstep=True,dtype=float,axis=-1)
aray
p.plot(aray)

ModuleNotFoundError: No module named 'pylab'

In [98]:
arrr=np.eye(3,4)
arrr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [97]:
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [144]:
b=np.random.rand(2,5)
b

array([[0.14560039, 0.70865539, 0.01048784, 0.95036639, 0.88757326],
       [0.56682277, 0.7809055 , 0.71909695, 0.35439431, 0.9792159 ]])

In [161]:
lis=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr=np.array(lis)

print(lis)
print(arr)
print('****************************')

print(arr[2:4,1:3])




[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
****************************
[[10 11]
 [14 15]]


In [168]:
print(arr>10)
print(arr[(arr>10) & (arr<15)])


[[False False False False]
 [False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[11 12 13 14]


In [169]:
arr[arr>10]=50
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 50, 50],
       [50, 50, 50, 50]])

In [173]:
ind=np.where(arr<50)
ind

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1]))

In [181]:
a = np.array([0, 1, 2, 3,9])
a.shape


(5,)

In [182]:
import numpy as np

def cut_rope(length, num_parts):
    # Generate cut points using numpy.linspace
    cut_points = np.linspace(0, length, num_parts + 1)[1:]  # Skip the first point (0) and include the rest
    
    # Round the cut points to 2 decimal places
    cut_points_rounded = np.round(cut_points, 2)
    
    return cut_points_rounded

# Example usage
if __name__ == "__main__":
    rope_length = 5  # Length of the rope in meters
    num_parts = 9    # Number of parts to cut the rope into
    
    # Get the cut points
    cut_points = cut_rope(rope_length, num_parts)
    
    # Print each cut point on a new line
    for point in cut_points:
        print(point)

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44
5.0
