In [1]:
# Import numpy library
import numpy as np

# Cell 1: Markdown cell
### Datatypes

# Cell 2: Markdown cell
# Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

# Cell 3: Code cell
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

# Cell 4: Markdown cell
# You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

# Cell 5: Markdown cell
### Array math

# Cell 6: Markdown cell
# Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

# Cell 7: Code cell
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

# Cell 8: Code cell
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

# Cell 9: Code cell
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

# Cell 10: Code cell
# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

# Cell 11: Code cell
# Elementwise square root; produces the array
print(np.sqrt(x))

# Cell 12: Code cell
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Cell 13: Markdown cell
# You can also use the `@` operator which is equivalent to numpy's `dot` operator.

# Cell 14: Code cell
print(v @ w)

# Cell 15: Code cell
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

# Cell 16: Code cell
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

# Cell 17: Markdown cell
# Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

# Cell 18: Code cell
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

# Cell 19: Markdown cell
# You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

# Cell 20: Markdown cell
# Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

# Cell 21: Code cell
print(x)
print("transpose\n", x.T)

# Cell 22: Code cell
v = np.array([[1, 2, 3]])
print(v)
print("transpose\n", v.T)


int64 float64 int64
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
219
219
219
[29 67]
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
10
[4 6]
[3 7]
[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]
[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]
